#!/bin/sh

dev=/dev/fd0
if [ -n "$1" ]; then
	dev="$1"
fi

# try to remake 256boss.img if it's missing
if [ ! -f 256boss.img ]; then
	make || exit 1
fi

# safety check
if mount | grep ^$dev >/dev/null 2>&1; then
	echo "device $dev seems to be in use." >&2
	echo "Make sure it's the correct device, and unmount the following filesystems first:" >&2
	echo "" >&2
	mount | grep ^$dev >&2
	exit 1
fi

imgsz=`wc -c 256boss.img | awk '{print $1}'`
nsect=`echo "($imgsz + 511) / 512" | bc`
dd if=floppy.img of=$dev bs=512 count=$nsect

sync
